asterisk:
  system_user: asterisk
  acl:
    - 'auth.tenants.read'
    - 'confd.voicemails.*.update'
    - 'confd.voicemails.read'

wazo-agentd:
  system_user: wazo-agentd
  acl:
    - 'auth.tenants.read'

wazo-agentd-cli:
  system_user: root
  acl:
    - 'agentd.#'

wazo-agid:
  system_user: wazo-agid
  acl:
    - 'agentd.#'
    - 'auth.tenants.read'
    - 'auth.users.*.sessions.read'
    - 'auth.users.*.tokens.read'
    - 'confd.devices.*.autoprov.read'
    - 'confd.devices.*.synchronize.read'
    - 'confd.devices.read'
    - 'confd.groups.*.read'
    - 'confd.lines.*.devices.*.update'
    - 'confd.lines.read'
    - 'confd.users.*.forwards.#'
    - 'confd.users.*.services.*.*'
    - 'dird.directories.reverse.*.*.read'

wazo-auth:
  system_user: wazo-auth
  acl:
    - 'auth.tenants.read'
    - 'confd.users.*.read'

wazo-call-logd:
  system_user: wazo-call-logd
  acl:
    - 'auth.tenants.read'
    - 'confd.contexts.read'
    - 'confd.lines.read'
    - 'confd.users.*.read'

wazo-calld:
  system_user: www-data
  acl:
    - 'amid.action.Command.create'
    - 'amid.action.ConfBridgeList.create'
    - 'amid.action.ConfbridgeKick.create'
    - 'amid.action.ConfbridgeMute.create'
    - 'amid.action.ConfbridgeStartRecord.create'
    - 'amid.action.ConfbridgeStopRecord.create'
    - 'amid.action.ConfbridgeUnmute.create'
    - 'amid.action.MuteAudio.create'
    - 'amid.action.Redirect.create'
    - 'amid.action.Setvar.create'
    - 'amid.action.ShowDialplan.create'
    - 'auth.tenants.read'
    - 'confd.#'
    - 'websocketd'
    - 'websocketd.#'

wazo-chatd:
  system_user: wazo-chatd
  acl:
    - 'amid.action.DeviceStateList.create'
    - 'auth.sessions.read'
    - 'auth.tenants.read'
    - 'auth.tokens.read'
    - 'confd.users.read'

wazo-confd:
  system_user: www-data
  acl:
    - 'auth.admin.#'
    - 'auth.tenants.read'
    - 'auth.users.#'
    - 'provd.#'

wazo-dird:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'auth.users.*.read'

wazo-dird-conference-backend:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'confd.conferences.read'

wazo-dird-wazo-backend:
  system_user: www-data
  acl:
    - 'auth.tenants.read'
    - 'confd.infos.read'
    - 'confd.users.read'

wazo-dxtora:
  system_user: wazo-dxtora
  acl:
    - 'provd.dev_mgr.dhcpinfo.create'

wazo-phoned:
  system_user: www-data
  acl:
    - 'amid.action.Command.create'
    - 'auth.tenants.read'
    - 'auth.users.*.read'
    - 'confd.extensions.features.read'
    - 'dird.directories.lookup.*.*.read'

wazo-plugind:
  system_user: wazo-plugind
  acl:
    - 'confd.infos.read'

wazo-plugind-cli:
  system_user: root
  acl:
    - 'plugind.#'

wazo-provd:
  system_user: wazo-provd
  acl:
    - 'amid.action.PJSIPNotify.create'
    - 'auth.tenants.read'

wazo-provd-cli:
  system_user: root
  acl:
    - 'provd.#'

wazo-upgrade:
  system_user: root
  acl:
    - 'auth.#'
    - 'confd.#'
    - 'dird.#'
    - 'plugind.#'
    - 'provd.#'
    - 'webhookd.#'

wazo-webhookd:
  system_user: wazo-webhookd
  acl:
    - 'auth.mobile.external.config.read'
    - 'auth.users.*.external.mobile.read'
    - 'auth.users.*.read'

xivo-wizard:
  system_user: www-data
  acl:
    - 'auth.policies.read'
    - 'auth.users.*.policies.*.create'
    - 'auth.users.create'
    - 'provd.cfg_mgr.configs.create'
    - 'provd.status.read'
